version: '3'

services:
    server:
        build: .
        container_name: server_check_connection
        volumes:
            - .:/usr/src/app
        ports:
            - 4001:4001
        command: npm run start:prod